{{- if or .Values.loki.enabled .Values.promtail.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.loki "name" "loki" "defaults" (include "bigbang.defaults.loki" .)) }}
{{- end }}

{{- define "bigbang.defaults.loki" -}}
loki:
  enabled: false

loki-simple-scalable:
  enabled: true

gel:
  enabled: true
  tokengen:
    annotations:
      sidecar.istio.io/inject: "false"

minio:
  makeBucketJob:
    podAnnotations:
      sidecar.istio.io/inject: "false"
{{- end -}}
